version: '3.1'

services:

  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres